#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-jsonlines
Version  : 3.0.0
Release  : 24
URL      : https://files.pythonhosted.org/packages/dd/fc/c207aafc82eb5d166b45723d9ff5844dde55474e0fc14f8180326779b996/jsonlines-3.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/dd/fc/c207aafc82eb5d166b45723d9ff5844dde55474e0fc14f8180326779b996/jsonlines-3.0.0.tar.gz
Summary  : Library with helpers for the jsonlines file format
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-jsonlines-license = %{version}-%{release}
Requires: pypi-jsonlines-python = %{version}-%{release}
Requires: pypi-jsonlines-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(attrs)

%description
.. image:: https://travis-ci.org/wbolster/jsonlines.svg?branch=master
:target: https://travis-ci.org/wbolster/jsonlines

%package license
Summary: license components for the pypi-jsonlines package.
Group: Default

%description license
license components for the pypi-jsonlines package.


%package python
Summary: python components for the pypi-jsonlines package.
Group: Default
Requires: pypi-jsonlines-python3 = %{version}-%{release}

%description python
python components for the pypi-jsonlines package.


%package python3
Summary: python3 components for the pypi-jsonlines package.
Group: Default
Requires: python3-core
Provides: pypi(jsonlines)
Requires: pypi(attrs)

%description python3
python3 components for the pypi-jsonlines package.


%prep
%setup -q -n jsonlines-3.0.0
cd %{_builddir}/jsonlines-3.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649770991
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jsonlines
cp %{_builddir}/jsonlines-3.0.0/LICENSE.rst %{buildroot}/usr/share/package-licenses/pypi-jsonlines/959c240e9ef9350dfc07d6c941ebe009a859268f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jsonlines/959c240e9ef9350dfc07d6c941ebe009a859268f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
